name: Python
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Lint and format
      run: |
        poetry run flake8 --select F torch_dataset settings
        poetry run black --check torch_dataset settings
    - name: Check types
      run: |
        poetry run mypy torch_dataset settings